# Generated by Django 4.2.18 on 2025-01-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0005_rename_text_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='posts/%Y%m%d', verbose_name='이미지'),
        ),
    ]
