# Generated by Django 4.2.18 on 2025-01-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0007_post_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
