# Generated by Django 4.2.18 on 2025-01-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='posts/%Y%m%d', verbose_name='이미지')),
                ('content', models.TextField()),
                ('interest', models.IntegerField(default=0, verbose_name='아이디어 관심도')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='demos.devtool')),
            ],
        ),
    ]
