# Generated by Django 4.2.17 on 2025-01-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
