# Generated by Django 4.2.17 on 2025-01-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('year', models.TextField()),
                ('genre', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=5)),
                ('time', models.TextField()),
                ('review', models.TextField()),
                ('director', models.TextField()),
                ('actor', models.TextField()),
            ],
        ),
    ]
